version: "3.9"
services:
  menu_service:
    build: ./menu_service
    volumes:
      - ./menu_service:/usr/src/app
    ports:
      - '3000:3000'
    depends_on: 
      - db 
    environment:
      RACK_ENV: 'development'
      DATABASE_URL: 'postgres://cardapio:cardapio@db:5432/cardapio'
  db:
    image: postgres:13-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment: 
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: cardapio
      POSTGRES_PASSWORD: cardapio

volumes:
  db-volume: