version: "3.9"
services:
  menu-service:
    build: ./menu-service
    volumes:
      - ./menu-service:/usr/src/app
    ports:
      - "3000:3000"
    depends_on: 
      - db 
  db:
    image: postgres:13-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment: 
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: cardapio
      POSTGRES_PASSWORD: cardapio
volumes:
  db-volume: