version: "3.9"
services:
  auth_service:
    build: ./auth_service
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://auth:auth@db:5432/auth?schema_path=auth
      - PASSWORD_DATABASE_URL=postgres://auth_password:auth_password@db:5432/auth?schema_path=auth_password
      - SESSION_SECRET=bod&F069|)x|Rc)OYqau'_J.bP3k>zH9|QSVGRA~7ekiY;bW_KeA~]88%m1fkto
    volumes:
      - ./auth_service:/usr/src/app
  menu_service:
    build: ./menu_service
    ports:
      - '3000:3000'
    depends_on: 
      - db 
    environment:
      - RACK_ENV=development
      - DATABASE_URL=postgres://cardapio:cardapio@db:5432/cardapio
    volumes:
      - ./menu_service:/usr/src/app
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment: 
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=cardapio
      - POSTGRES_PASSWORD=cardapio
    volumes:
      - db-volume:/var/lib/postgresql/data
volumes:
  db-volume:
