source 'https://rubygems.org'
ruby '3.0.0' 
 
# http server
gem 'roda', '~> 3.40.0'
gem 'puma'
gem 'rack-unreloader'

# database
gem 'pg'
gem 'sequel'
gem 'sequel_postgresql_triggers'

# runner
gem 'rake'

# testing
group :development, :test do
  gem 'minitest'
end