apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    run: auth-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    run: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: auth-service
  template:
    metadata:
      labels:
        run: auth-service
    spec:
      initContainers:
      - image: creativename/auth-service
        name: init-auth-service-migration
        command: ["sh", "-c"]
        args: ["bin/rake db:migrate && bin/rake db:migrate_password"]
        env:
        - name: DATABASE_URL
          value: "postgres://auth:auth@postgres-svc.default.svc.cluster.local:5432/auth?search_path=auth,auth_password"
        - name: PASSWORD_DATABASE_URL
          value: "postgres://auth_password:auth_password@postgres-svc.default.svc.cluster.local:5432/auth?search_path=auth_password"
        - name: DATABASE_NAME
          value: "auth"
      containers:
      - image: creativename/auth-service
        imagePullPolicy: Always
        name: auth-service
        env:
        - name: RACK_ENV
          value: "development"
        - name: DATABASE_URL
          value: "postgres://auth:auth@postgres-svc.default.svc.cluster.local:5432/auth?search_path=auth,auth_password"
        - name: PASSWORD_DATABASE_URL
          value: "postgres://auth_password:auth_password@postgres-svc.default.svc.cluster.local:5432/auth?search_path=auth_password"
        - name: DATABASE_NAME
          value: "auth"
        - name: SESSION_SECRET
          value: "bod&F069|)x|Rc)OYqau'_J.bP3k>zH9|QSVGRA~7ekiY;bW_KeA~]88%m1fktoNz"
        ports:
        - containerPort: 3000
