require 'rake/testtask'
require 'rake/clean'

namespace :db do
  desc 'Run migrations'
  task :migrate, [:version] do |t, args|
    require 'sequel/core'
    Sequel.extension :migration
    version = args[:version].to_i if args[:version]
    Sequel.connect(ENV['DATABASE_URL']) do |db|
      Sequel::Migrator.run(db, 'db/migrate', target: version)
    end
  end

  task :migrate_password, [:version] do |t, args|
    require 'sequel/core'
    Sequel.extension :migration
    version = args[:version].to_i if args[:version]
    Sequel.connect(ENV['PASSWORD_DATABASE_URL']) do |db|
      Sequel::Migrator.run(db, 'db/migrate_password', :table=>'schema_info_password', :target=>version)
    end
  end
end