source 'https://rubygems.org'
ruby '3.0.0' 
 
# server
gem 'roda', '~> 3.40.0'
gem 'puma'
gem 'rack-unreloader'

# database
gem 'sequel'
gem 'sqlite3', group: :test
group :development, :production do
  gem 'pg'
  gem 'sequel_postgresql_triggers'
end

# debugging
gem 'byebug', group: %i(development test)

# testing
group :test do
  gem 'minitest'
  gem 'minitest-hooks'
  gem 'rack-test'
end
